// Code generated by go-swagger; DO NOT EDIT.

package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/klingo/app/stapi/models"
)

// GetCharacterReader is a Reader for the GetCharacter structure.
type GetCharacterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharacterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCharacterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCharacterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCharacterOK creates a GetCharacterOK with default headers values
func NewGetCharacterOK() *GetCharacterOK {
	return &GetCharacterOK{}
}

/*GetCharacterOK handles this case with default header values.

Detailed description of a character
*/
type GetCharacterOK struct {
	Payload *models.CharacterFullResponse
}

func (o *GetCharacterOK) Error() string {
	return fmt.Sprintf("[GET /character][%d] getCharacterOK  %+v", 200, o.Payload)
}

func (o *GetCharacterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CharacterFullResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharacterDefault creates a GetCharacterDefault with default headers values
func NewGetCharacterDefault(code int) *GetCharacterDefault {
	return &GetCharacterDefault{
		_statusCode: code,
	}
}

/*GetCharacterDefault handles this case with default header values.

Unexpected error
*/
type GetCharacterDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get character default response
func (o *GetCharacterDefault) Code() int {
	return o._statusCode
}

func (o *GetCharacterDefault) Error() string {
	return fmt.Sprintf("[GET /character][%d] GetCharacter default  %+v", o._statusCode, o.Payload)
}

func (o *GetCharacterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
