// Code generated by go-swagger; DO NOT EDIT.

package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/klingo/app/stapi/models"
)

// PostCharacterSearchReader is a Reader for the PostCharacterSearch structure.
type PostCharacterSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCharacterSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostCharacterSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostCharacterSearchOK creates a PostCharacterSearchOK with default headers values
func NewPostCharacterSearchOK() *PostCharacterSearchOK {
	return &PostCharacterSearchOK{}
}

/*PostCharacterSearchOK handles this case with default header values.

List of characters
*/
type PostCharacterSearchOK struct {
	Payload *models.CharacterBaseResponse
}

func (o *PostCharacterSearchOK) Error() string {
	return fmt.Sprintf("[POST /character/search][%d] postCharacterSearchOK  %+v", 200, o.Payload)
}

func (o *PostCharacterSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CharacterBaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
