// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CharacterFull Full character, returned when queried using UID
// swagger:model CharacterFull
type CharacterFull struct {

	// Whether this character is from alternate reality
	AlternateReality bool `json:"alternateReality,omitempty"`

	// Blood type
	BloodType BloodType `json:"bloodType,omitempty"`

	// Relations with other characters
	CharacterRelations []*CharacterRelation `json:"characterRelations"`

	// Species this character belongs to
	CharacterSpecies []*CharacterSpecies `json:"characterSpecies"`

	// Day the character was born
	DayOfBirth int64 `json:"dayOfBirth,omitempty"`

	// Day the character died
	DayOfDeath int64 `json:"dayOfDeath,omitempty"`

	// Whether this character is deceased
	Deceased bool `json:"deceased,omitempty"`

	// Episodes in which this character appeared
	Episodes []*EpisodeBase `json:"episodes"`

	// Whether this character is a fictional character (from universe point of view)
	FictionalCharacter bool `json:"fictionalCharacter,omitempty"`

	// Character gender
	Gender Gender `json:"gender,omitempty"`

	// Height in centimeters
	Height int64 `json:"height,omitempty"`

	// Whether this character is a hologram
	Hologram bool `json:"hologram,omitempty"`

	// Hologram activation date
	HologramActivationDate string `json:"hologramActivationDate,omitempty"`

	// Hologram date status
	HologramDateStatus string `json:"hologramDateStatus,omitempty"`

	// Hologram status
	HologramStatus string `json:"hologramStatus,omitempty"`

	// Marital status
	MaritalStatus MaritalStatus `json:"maritalStatus,omitempty"`

	// Whether this character is from mirror universe
	Mirror bool `json:"mirror,omitempty"`

	// Month the character was born
	MonthOfBirth int64 `json:"monthOfBirth,omitempty"`

	// Month the character died
	MonthOfDeath int64 `json:"monthOfDeath,omitempty"`

	// Movies in which this character appeared
	Movies []*MovieBase `json:"movies"`

	// Character name
	Name string `json:"name,omitempty"`

	// Occupations of this character
	Occupations []*OccupationBase `json:"occupations"`

	// Organizations this character has affiliation with
	Organizations []*OrganizationBase `json:"organizations"`

	// Performers who played this character
	Performers []*PerformerBase `json:"performers"`

	// Place of birth
	PlaceOfBirth string `json:"placeOfBirth,omitempty"`

	// Place of death
	PlaceOfDeath string `json:"placeOfDeath,omitempty"`

	// Serial number
	SerialNumber string `json:"serialNumber,omitempty"`

	// Titles this character holds
	Titles []*TitleBase `json:"titles"`

	// Character unique ID
	UID string `json:"uid,omitempty"`

	// Weight in kilograms
	Weight int64 `json:"weight,omitempty"`

	// Year the character was born
	YearOfBirth int64 `json:"yearOfBirth,omitempty"`

	// Year the character died
	YearOfDeath int64 `json:"yearOfDeath,omitempty"`
}

// Validate validates this character full
func (m *CharacterFull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBloodType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCharacterRelations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCharacterSpecies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEpisodes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaritalStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMovies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOccupations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePerformers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CharacterFull) validateBloodType(formats strfmt.Registry) error {

	if swag.IsZero(m.BloodType) { // not required
		return nil
	}

	if err := m.BloodType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("bloodType")
		}
		return err
	}

	return nil
}

func (m *CharacterFull) validateCharacterRelations(formats strfmt.Registry) error {

	if swag.IsZero(m.CharacterRelations) { // not required
		return nil
	}

	for i := 0; i < len(m.CharacterRelations); i++ {
		if swag.IsZero(m.CharacterRelations[i]) { // not required
			continue
		}

		if m.CharacterRelations[i] != nil {
			if err := m.CharacterRelations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("characterRelations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateCharacterSpecies(formats strfmt.Registry) error {

	if swag.IsZero(m.CharacterSpecies) { // not required
		return nil
	}

	for i := 0; i < len(m.CharacterSpecies); i++ {
		if swag.IsZero(m.CharacterSpecies[i]) { // not required
			continue
		}

		if m.CharacterSpecies[i] != nil {
			if err := m.CharacterSpecies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("characterSpecies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateEpisodes(formats strfmt.Registry) error {

	if swag.IsZero(m.Episodes) { // not required
		return nil
	}

	for i := 0; i < len(m.Episodes); i++ {
		if swag.IsZero(m.Episodes[i]) { // not required
			continue
		}

		if m.Episodes[i] != nil {
			if err := m.Episodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("episodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateGender(formats strfmt.Registry) error {

	if swag.IsZero(m.Gender) { // not required
		return nil
	}

	if err := m.Gender.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("gender")
		}
		return err
	}

	return nil
}

func (m *CharacterFull) validateMaritalStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.MaritalStatus) { // not required
		return nil
	}

	if err := m.MaritalStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("maritalStatus")
		}
		return err
	}

	return nil
}

func (m *CharacterFull) validateMovies(formats strfmt.Registry) error {

	if swag.IsZero(m.Movies) { // not required
		return nil
	}

	for i := 0; i < len(m.Movies); i++ {
		if swag.IsZero(m.Movies[i]) { // not required
			continue
		}

		if m.Movies[i] != nil {
			if err := m.Movies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("movies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateOccupations(formats strfmt.Registry) error {

	if swag.IsZero(m.Occupations) { // not required
		return nil
	}

	for i := 0; i < len(m.Occupations); i++ {
		if swag.IsZero(m.Occupations[i]) { // not required
			continue
		}

		if m.Occupations[i] != nil {
			if err := m.Occupations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("occupations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateOrganizations(formats strfmt.Registry) error {

	if swag.IsZero(m.Organizations) { // not required
		return nil
	}

	for i := 0; i < len(m.Organizations); i++ {
		if swag.IsZero(m.Organizations[i]) { // not required
			continue
		}

		if m.Organizations[i] != nil {
			if err := m.Organizations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("organizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validatePerformers(formats strfmt.Registry) error {

	if swag.IsZero(m.Performers) { // not required
		return nil
	}

	for i := 0; i < len(m.Performers); i++ {
		if swag.IsZero(m.Performers[i]) { // not required
			continue
		}

		if m.Performers[i] != nil {
			if err := m.Performers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("performers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterFull) validateTitles(formats strfmt.Registry) error {

	if swag.IsZero(m.Titles) { // not required
		return nil
	}

	for i := 0; i < len(m.Titles); i++ {
		if swag.IsZero(m.Titles[i]) { // not required
			continue
		}

		if m.Titles[i] != nil {
			if err := m.Titles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("titles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CharacterFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterFull) UnmarshalBinary(b []byte) error {
	var res CharacterFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
