// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CharacterBaseResponse Response object for characters search
// swagger:model CharacterBaseResponse
type CharacterBaseResponse struct {

	// List of characters matching given criteria
	Characters []*CharacterBase `json:"characters"`

	// Response page
	Page *ResponsePage `json:"page,omitempty"`

	// Response sort
	Sort *ResponseSort `json:"sort,omitempty"`
}

// Validate validates this character base response
func (m *CharacterBaseResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCharacters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CharacterBaseResponse) validateCharacters(formats strfmt.Registry) error {

	if swag.IsZero(m.Characters) { // not required
		return nil
	}

	for i := 0; i < len(m.Characters); i++ {
		if swag.IsZero(m.Characters[i]) { // not required
			continue
		}

		if m.Characters[i] != nil {
			if err := m.Characters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("characters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CharacterBaseResponse) validatePage(formats strfmt.Registry) error {

	if swag.IsZero(m.Page) { // not required
		return nil
	}

	if m.Page != nil {
		if err := m.Page.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("page")
			}
			return err
		}
	}

	return nil
}

func (m *CharacterBaseResponse) validateSort(formats strfmt.Registry) error {

	if swag.IsZero(m.Sort) { // not required
		return nil
	}

	if m.Sort != nil {
		if err := m.Sort.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sort")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CharacterBaseResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterBaseResponse) UnmarshalBinary(b []byte) error {
	var res CharacterBaseResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
