// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CharacterHeader Header character, embedded in other objects
// swagger:model CharacterHeader
type CharacterHeader struct {

	// Character name
	Name string `json:"name,omitempty"`

	// Character unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this character header
func (m *CharacterHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CharacterHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterHeader) UnmarshalBinary(b []byte) error {
	var res CharacterHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
