// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CharacterSpecies Species a character belongs to
// swagger:model CharacterSpecies
type CharacterSpecies struct {

	// Denominator
	Denominator int64 `json:"denominator,omitempty"`

	// Species name
	Name string `json:"name,omitempty"`

	// Numerator
	Numerator int64 `json:"numerator,omitempty"`

	// Entity unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this character species
func (m *CharacterSpecies) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CharacterSpecies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterSpecies) UnmarshalBinary(b []byte) error {
	var res CharacterSpecies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
