// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CharacterFullResponse Response object for single character query
// swagger:model CharacterFullResponse
type CharacterFullResponse struct {

	// Character, if found
	Character *CharacterFull `json:"character,omitempty"`
}

// Validate validates this character full response
func (m *CharacterFullResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCharacter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CharacterFullResponse) validateCharacter(formats strfmt.Registry) error {

	if swag.IsZero(m.Character) { // not required
		return nil
	}

	if m.Character != nil {
		if err := m.Character.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("character")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CharacterFullResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterFullResponse) UnmarshalBinary(b []byte) error {
	var res CharacterFullResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
