// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Gender Gender
// swagger:model Gender
type Gender string

const (

	// GenderF captures enum value "F"
	GenderF Gender = "F"

	// GenderM captures enum value "M"
	GenderM Gender = "M"
)

// for schema
var genderEnum []interface{}

func init() {
	var res []Gender
	if err := json.Unmarshal([]byte(`["F","M"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		genderEnum = append(genderEnum, v)
	}
}

func (m Gender) validateGenderEnum(path, location string, value Gender) error {
	if err := validate.Enum(path, location, value, genderEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this gender
func (m Gender) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGenderEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
