// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OrganizationBase Base organization, returned in search results
// swagger:model OrganizationBase
type OrganizationBase struct {

	// Whether this location is from alternate reality
	AlternateReality bool `json:"alternateReality,omitempty"`

	// Whether it's a government
	Government bool `json:"government,omitempty"`

	// Whether it's a government agency
	GovernmentAgency bool `json:"governmentAgency,omitempty"`

	// Whether it's an intergovernmental organization
	IntergovernmentalOrganization bool `json:"intergovernmentalOrganization,omitempty"`

	// Whether it's a law enforcement agency
	LawEnforcementAgency bool `json:"lawEnforcementAgency,omitempty"`

	// Whether it's a medical organization
	MedicalOrganization bool `json:"medicalOrganization,omitempty"`

	// Whether it's a military organization
	MilitaryOrganization bool `json:"militaryOrganization,omitempty"`

	// Whether it's a military unit
	MilitaryUnit bool `json:"militaryUnit,omitempty"`

	// Whether this organization is from mirror universe
	Mirror bool `json:"mirror,omitempty"`

	// Organization name
	Name string `json:"name,omitempty"`

	// Whether it's a prison or penal colony
	PrisonOrPenalColony bool `json:"prisonOrPenalColony,omitempty"`

	// Whether it's a research organization
	ResearchOrganization bool `json:"researchOrganization,omitempty"`

	// Whether it's a sport organization
	SportOrganization bool `json:"sportOrganization,omitempty"`

	// Organization unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this organization base
func (m *OrganizationBase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationBase) UnmarshalBinary(b []byte) error {
	var res OrganizationBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
