// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ResponseSortDirection Sort direction
// swagger:model ResponseSortDirection
type ResponseSortDirection string

const (

	// ResponseSortDirectionASC captures enum value "ASC"
	ResponseSortDirectionASC ResponseSortDirection = "ASC"

	// ResponseSortDirectionDESC captures enum value "DESC"
	ResponseSortDirectionDESC ResponseSortDirection = "DESC"
)

// for schema
var responseSortDirectionEnum []interface{}

func init() {
	var res []ResponseSortDirection
	if err := json.Unmarshal([]byte(`["ASC","DESC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		responseSortDirectionEnum = append(responseSortDirectionEnum, v)
	}
}

func (m ResponseSortDirection) validateResponseSortDirectionEnum(path, location string, value ResponseSortDirection) error {
	if err := validate.Enum(path, location, value, responseSortDirectionEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this response sort direction
func (m ResponseSortDirection) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateResponseSortDirectionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
