// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SeasonHeader Header season, embedded in other objects
// swagger:model seasonHeader
type SeasonHeader struct {

	// Season title
	Title string `json:"title,omitempty"`

	// Season unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this season header
func (m *SeasonHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SeasonHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeasonHeader) UnmarshalBinary(b []byte) error {
	var res SeasonHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
