// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SeriesHeader Header series, embedded in other objects
// swagger:model seriesHeader
type SeriesHeader struct {

	// Series title
	Title string `json:"title,omitempty"`

	// Series unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this series header
func (m *SeriesHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SeriesHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeriesHeader) UnmarshalBinary(b []byte) error {
	var res SeriesHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
