// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TitleBase Base title, returned in search results
// swagger:model TitleBase
type TitleBase struct {

	// Whether it's a fleet rank
	FleetRank bool `json:"fleetRank,omitempty"`

	// Whether it's a military rank
	MilitaryRank bool `json:"militaryRank,omitempty"`

	// Whether this title is from mirror universe
	Mirror bool `json:"mirror,omitempty"`

	// Title name
	Name string `json:"name,omitempty"`

	// Whether it's a position
	Position bool `json:"position,omitempty"`

	// Whether it's a religious title
	ReligiousTitle bool `json:"religiousTitle,omitempty"`

	// Title unique ID
	UID string `json:"uid,omitempty"`
}

// Validate validates this title base
func (m *TitleBase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TitleBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TitleBase) UnmarshalBinary(b []byte) error {
	var res TitleBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
